# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS commonHeaders Threading CoordXform GeoSpaceTime CTimeValue_shared TimeConv_c_shared CTimeValue TimeConv_c VectorOps FloatMath AbMatrix fio UnitTestOutput spwxcommon modelsHeaders cmagfield cmagfield_shared shielddose2 shielddose2_shared radenv radenv_shared cammice adiabat orbitprop orbitprop_shared)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target commonHeaders
add_library(commonHeaders INTERFACE IMPORTED)

set_target_properties(commonHeaders PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Threading
add_library(Threading STATIC IMPORTED)

# Create imported target CoordXform
add_library(CoordXform STATIC IMPORTED)

# Create imported target GeoSpaceTime
add_library(GeoSpaceTime STATIC IMPORTED)

# Create imported target CTimeValue_shared
add_library(CTimeValue_shared SHARED IMPORTED)

# Create imported target TimeConv_c_shared
add_library(TimeConv_c_shared SHARED IMPORTED)

# Create imported target CTimeValue
add_library(CTimeValue STATIC IMPORTED)

# Create imported target TimeConv_c
add_library(TimeConv_c STATIC IMPORTED)

# Create imported target VectorOps
add_library(VectorOps STATIC IMPORTED)

# Create imported target FloatMath
add_library(FloatMath STATIC IMPORTED)

# Create imported target AbMatrix
add_library(AbMatrix STATIC IMPORTED)

# Create imported target fio
add_library(fio STATIC IMPORTED)

# Create imported target UnitTestOutput
add_library(UnitTestOutput STATIC IMPORTED)

# Create imported target spwxcommon
add_library(spwxcommon STATIC IMPORTED)

# Create imported target modelsHeaders
add_library(modelsHeaders INTERFACE IMPORTED)

set_target_properties(modelsHeaders PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target cmagfield
add_library(cmagfield STATIC IMPORTED)

# Create imported target cmagfield_shared
add_library(cmagfield_shared SHARED IMPORTED)

set_target_properties(cmagfield_shared PROPERTIES
  INTERFACE_LINK_LIBRARIES "spwxcommon;hdf5::hdf5-static;hdf5::hdf5_cpp-static;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libz.lib;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libaec.lib"
)

# Create imported target shielddose2
add_library(shielddose2 STATIC IMPORTED)

# Create imported target shielddose2_shared
add_library(shielddose2_shared SHARED IMPORTED)

set_target_properties(shielddose2_shared PROPERTIES
  INTERFACE_LINK_LIBRARIES "spwxcommon;hdf5::hdf5-static;hdf5::hdf5_cpp-static;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libz.lib;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libaec.lib"
)

# Create imported target radenv
add_library(radenv STATIC IMPORTED)

# Create imported target radenv_shared
add_library(radenv_shared SHARED IMPORTED)

set_target_properties(radenv_shared PROPERTIES
  INTERFACE_LINK_LIBRARIES "cmagfield;shielddose2;spwxcommon;hdf5::hdf5-static;hdf5::hdf5_cpp-static;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libz.lib;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libaec.lib"
)

# Create imported target cammice
add_library(cammice STATIC IMPORTED)

# Create imported target adiabat
add_library(adiabat STATIC IMPORTED)

# Create imported target orbitprop
add_library(orbitprop STATIC IMPORTED)

# Create imported target orbitprop_shared
add_library(orbitprop_shared SHARED IMPORTED)

set_target_properties(orbitprop_shared PROPERTIES
  INTERFACE_LINK_LIBRARIES "spwxcommon;hdf5::hdf5-static;hdf5::hdf5_cpp-static;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libz.lib;C:/Program Files/HDF_Group/HDF5/1.14.1/lib/libaec.lib"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/spwx-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
